[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "python-ed2k"
version = "0.1.0"
description = "Typed asyncio client for goed2k"
readme = "README.md"
requires-python = ">=3.11"

[tool.ruff]
line-length = 100

[tool.setuptools.packages.find]
include = ["python_ed2k*"]
